### ISSUE TITLE
emm 没有合适的decord版本，这个包好像不是很常用吧，作者能不能改改嘛感谢了。

### ISSUE THREAD

**Issue by haihaict** [AIFSH/ComfyUI-MimicMotion#14]
默认的SD python环境都是3.10的，这个decord只适配到3.8.我甚至不能force install。么么

**Comment by baicai99** [comment]
ComfyUI官方版本应该是venv启动的，内置py环境，你可以尝试下载官方版本。https://github.com/comfyanonymous/ComfyUI/releases/download/latest/ComfyUI_windows_portable_nvidia_cu121_or_cpu.7z
或者下载我打包好的：https://www.liblib.art/modelinfo/83d4b008867e4738a07b49a0af3310f8?from=personal_page

**Comment by haihaict** [comment]
> ComfyUI官方版本应该是venv启动的，内置py环境，你可以尝试下载官方版本。https://github.com/comfyanonymous/ComfyUI/releases/download/latest/ComfyUI_windows_portable_nvidia_cu121_or_cpu.7z 或者下载我打包好的：https://www.liblib.art/modelinfo/83d4b008867e4738a07b49a0af3310f8?from=personal_page

谢谢你，我是mac。我傻了，默认的版本是装不了的，m芯片的decord要装 eva-decord

**Comment by haihaict** [comment]
m chip mac install eva-decord.
